#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          15

# Border colors
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"
# bspc config urgent_border_color "#B58900"
# bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config paddingless_monocle  true
bspc config top_monocle_padding  -2

# bspc rule -a Brave-browser state=floating rectangle=1520x855+200+125
bspc rule -a Brave-browser rectangle=1520x855+200+125
bspc rule -a Alacritty rectangle=1520x855+200+125
bspc rule -a Zathura rectangle=900x1000+532+50

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
